name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          pip install flet
          # Se você tiver um arquivo de requisitos, descomente a linha abaixo:
          # pip install -r requirements.txt

      - name: Flet Build APK
        run: |
          # Adicionamos o verbose para detalhar erros se o build falhar
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-final
          # Ajuste do caminho: o Flet 0.22+ gera na pasta build/apk
          path: build/apk/*.apk
