name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          # Se tiveres um ficheiro requirements.txt, ele será instalado aqui
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Flet Build APK
        run: |
          # O comando 'flet build apk' compila o projeto
          # Adicionamos o verbose para identificar erros nos logs do GitHub
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: meu-app-final
          # O caminho padrão onde o Flet guarda o APK gerado
          path: build/apk/*.apk
          if-no-files-found: error
